const products = [
  {id:"cup",name:"Form cup",subtitle:"Speckled stoneware · Set of 2",category:"Ceramics",price:48,was:56,rating:4.9,reviews:128,badge:"Small batch",image:"photo-1578749556568-bc2c40e68b61",alt:"photo-1493106641515-6b5631de4bb9",colors:[["Oat","#d5c5a9"],["Moss","#7d8970"],["Chalk","#eeece3"]],description:"A quietly considered cup with a comfortable weight and a hand-glazed finish. Each one carries the small, lovely marks of the maker.",benefits:["Wheel-thrown in small batches","Food-safe, lead-free glaze","Dishwasher and microwave safe"]},
  {id:"tote",name:"Daily carryall",subtitle:"Recycled cotton canvas",category:"Textiles",price:64,rating:4.8,reviews:96,badge:"Best seller",image:"photo-1544816155-12df9643f363",alt:"photo-1590874103328-eac38a683ce7",colors:[["Natural","#d6ccb7"],["Olive","#727d5b"]],description:"The dependable, do-everything carryall. Cut from sturdy recycled cotton with room for market finds, daily essentials, and one more thing.",benefits:["Made with 70% recycled cotton","Reinforced handles for everyday weight","Interior pocket keeps small things close"]},
  {id:"vase",name:"Arc bud vase",subtitle:"Hand-finished stoneware",category:"Ceramics",price:72,rating:5,reviews:42,badge:"Maker’s pick",image:"photo-1578500494198-246f612d3b3d",alt:"photo-1576021182211-9ea8dced3690",colors:[["Clay","#bd745b"],["Ivory","#e6e0d3"]],description:"A sculptural little home for a single stem or a few things gathered on a walk. Its softly curved form looks good with or without flowers.",benefits:["Hand-shaped by independent potters","Watertight, satin-matte glaze","Every piece has its own gentle variation"]},
  {id:"throw",name:"Sunday throw",subtitle:"Washed European linen",category:"Textiles",price:138,was:158,rating:4.9,reviews:73,badge:"Small batch",image:"photo-1600210491892-03d54c0aaf87",alt:"photo-1616486338812-3dadae4b4ace",colors:[["Rust","#ac614b"],["Flax","#c9c0ac"],["Green","#697b67"]],description:"A soft, breathable layer for late mornings, cooler evenings, and the spaces in between. Woven from European flax and washed until it feels like yours.",benefits:["100% European flax linen","Gets softer with every wash","Responsibly woven in small runs"]},
  {id:"board",name:"Field board",subtitle:"Responsibly sourced oak",category:"Home",price:86,rating:4.7,reviews:51,badge:"New",image:"photo-1603073163308-9654c3fb70b5",alt:"photo-1600566753086-00f18fb6b3ea",colors:[["Natural oak","#ba9366"],["Smoked oak","#685447"]],description:"A sturdy, generous board for the everyday rituals around a table. Made from responsibly sourced oak that looks better with a little use.",benefits:["FSC-certified European oak","Finished with food-safe oil","Handmade and easy to care for"]},
  {id:"bowl",name:"Daily bowl",subtitle:"Reclaimed clay · Set of 2",category:"Ceramics",price:58,rating:4.9,reviews:84,badge:"Small batch",image:"photo-1610701596007-11502861dcfa",alt:"photo-1493106641515-6b5631de4bb9",colors:[["Salt","#e6e0d3"],["Earth","#a86b54"]],description:"The bowl that earns its shelf space: generous enough for breakfast, dinner, or a handful of something good. Made with reclaimed local clay.",benefits:["Made with 30% reclaimed clay","A versatile 16 cm everyday size","Dishwasher and microwave safe"]},
  {id:"lamp",name:"Soft light lamp",subtitle:"Recycled glass · Warm LED",category:"Home",price:168,rating:4.8,reviews:37,badge:"Maker’s pick",image:"photo-1507473885765-e6ed057f782c",alt:"photo-1507473885765-e6ed057f782c",colors:[["Smoke","#68726e"],["Clear","#d9d7c8"]],description:"An easy pool of warm light for the bedside or the corner you always end up in. Each shade is shaped from recycled glass, so no two are quite alike.",benefits:["Shade made with recycled glass","Warm, energy-efficient LED included","Designed and assembled in small runs"]},
  {id:"candle",name:"Rest candle",subtitle:"Botanical wax · 45-hour burn",category:"Home",price:42,rating:4.9,reviews:112,badge:"A small ritual",image:"photo-1603006905003-be475563bc59",alt:"photo-1602874801007-bd458bb1b8b6",colors:[["Hinoki","#899078"],["Amber","#b7734c"]],description:"A gentle, woodsy scent to mark the end of a day. Poured in small batches with a clean-burning botanical wax blend.",benefits:["Coconut and soy wax blend","Cotton wick, no added dyes","Reusable glass vessel"]}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s), img=(id,w=800)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=82`;
let category="All",query="",variants={},cart=loadCart(),lastFocus,toastTimer;
const grid=$("#products"),drawer=$("#drawer"),modal=$("#product-modal"),overlay=$("#overlay"),toast=$(".toast"),reduceMotion=matchMedia("(prefers-reduced-motion: reduce)");
function loadCart(){try{const items=JSON.parse(localStorage.getItem("morrow-cart")||"[]");return Array.isArray(items)?items.filter(x=>products.some(p=>p.id===x.id)&&Number.isInteger(x.qty)&&x.qty>0):[]}catch{return[]}}
const money=n=>`$${n.toFixed(2)}`;
function render(){let list=products.filter(p=>(category==="All"||p.category===category)&&`${p.name} ${p.subtitle} ${p.category}`.toLowerCase().includes(query.toLowerCase()));const sort=$("#sort").value;if(sort==="low")list.sort((a,b)=>a.price-b.price);if(sort==="high")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);grid.innerHTML=list.map((p,i)=>`<article class="card" style="animation-delay:${Math.min(i*45,240)}ms"><div class="media" data-open="${p.id}"><img src="${img(p.image)}" alt="${p.name}, ${p.subtitle.toLowerCase()}" loading="lazy"><img class="secondary" src="${img(p.alt)}" alt="" loading="lazy"><span class="badge">${p.badge}</span><button class="quick" data-add="${p.id}" aria-label="Quick add ${p.name}">Quick add <span>+</span></button></div><div class="details"><div><h3 class="name"><button class="product-link" data-open="${p.id}">${p.name}</button></h3><p class="subtitle">${p.subtitle}</p></div><div class="price">${p.was?`<span class="old">${money(p.was)}</span>`:""}${money(p.price)}</div><p class="rating"><span aria-label="${p.rating} out of 5 stars">★★★★★</span>${p.rating.toFixed(1)} · ${p.reviews} reviews</p></div><div class="swatches" role="group" aria-label="${p.name} colors">${p.colors.map(([name,color],i)=>`<button class="swatch" style="background:${color}" aria-label="${name}" title="${name}" aria-pressed="${(variants[p.id]||p.colors[0][0])===name}" data-swatch="${p.id}" data-variant="${name}"></button>`).join("")}</div></article>`).join("");$(".no-results").hidden=!!list.length}
function updateCart(){const count=cart.reduce((s,x)=>s+x.qty,0),sum=cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);$(".bag-count").textContent=count;$(".drawer-count").textContent=`(${count})`;$(".subtotal strong").textContent=money(sum);drawer.classList.toggle("empty",!cart.length);const remaining=Math.max(0,100-sum);$(".shipping-msg").innerHTML=remaining?`You’re <strong>${money(remaining)}</strong> away from complimentary shipping.`:"You’ve unlocked complimentary shipping. Nice.";$(".progress span").style.width=`${Math.min(100,sum)}%`;$(".cart-lines").innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<article class="line"><img src="${img(p.image,200)}" alt=""><div class="line-info"><strong>${p.name}</strong><small>${x.variant}</small><div class="qty"><button data-qty="-1" data-id="${x.id}" data-variant="${x.variant}" aria-label="Decrease ${p.name} quantity">−</button><span>${x.qty}</span><button data-qty="1" data-id="${x.id}" data-variant="${x.variant}" aria-label="Increase ${p.name} quantity">+</button></div></div><span class="line-price">${money(p.price*x.qty)}</span></article>`}).join("")}
function persist(){localStorage.setItem("morrow-cart",JSON.stringify(cart))}
function add(id){const p=products.find(x=>x.id===id),variant=variants[id]||p.colors[0][0],found=cart.find(x=>x.id===id&&x.variant===variant);found?found.qty++:cart.push({id,variant,qty:1});persist();updateCart();say(`${p.name} added to your bag`)}
function say(text){toast.textContent=text;toast.classList.add("visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("visible"),2300)}
function showOverlay(){overlay.hidden=false;requestAnimationFrame(()=>overlay.classList.add("visible"));document.body.classList.add("lock")}
function hideOverlay(){overlay.classList.remove("visible");document.body.classList.remove("lock");setTimeout(()=>{if(!drawer.classList.contains("open")&&modal.hidden)overlay.hidden=true},reduceMotion.matches?0:250)}
function openDrawer(){lastFocus=document.activeElement;showOverlay();drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");$(".close").focus()}
function closeDrawer(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");if(modal.hidden)hideOverlay();lastFocus?.focus()}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;lastFocus=document.activeElement;$(".modal-body").innerHTML=`<img class="modal-image" src="${img(p.image,1000)}" alt="${p.name}, ${p.subtitle.toLowerCase()}"><div class="modal-info"><p class="eyebrow">${p.category} · ${p.badge}</p><h2>${p.name}</h2><p class="modal-rating"><span>★★★★★</span>${p.rating.toFixed(1)} · ${p.reviews} reviews</p><p class="modal-price">${money(p.price)} ${p.was?`<span class="old">${money(p.was)}</span>`:""}</p><p class="modal-description">${p.description}</p><ul class="benefits">${p.benefits.map(x=>`<li>${x}</li>`).join("")}</ul><span class="variant-label">Choose a finish</span><div class="variants" role="group" aria-label="Choose a finish">${p.colors.map(([name])=>`<button class="${(variants[id]||p.colors[0][0])===name?"selected":""}" data-modal-variant="${id}" data-variant="${name}" aria-pressed="${(variants[id]||p.colors[0][0])===name}">${name}</button>`).join("")}</div><button class="button dark modal-add" data-modal-add="${id}">Add to bag <span>${money(p.price)} ↗</span></button><p class="assurance">Free shipping over $100 · Easy 30-day returns</p></div>`;modal.hidden=false;modal.setAttribute("aria-hidden","false");showOverlay();requestAnimationFrame(()=>modal.classList.add("open"));$(".close-product").focus()}
function closeProduct(){modal.classList.remove("open");modal.hidden=true;modal.setAttribute("aria-hidden","true");if(!drawer.classList.contains("open"))hideOverlay();lastFocus?.focus()}
function setCategory(value){category=value;$$(".filter").forEach(b=>{const active=b.dataset.category===value;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))});render()}
grid.addEventListener("click",e=>{const addButton=e.target.closest("[data-add]"),swatch=e.target.closest("[data-swatch]"),card=e.target.closest("[data-open]");if(addButton){e.stopPropagation();add(addButton.dataset.add)}else if(swatch){variants[swatch.dataset.swatch]=swatch.dataset.variant;render()}else if(card)openProduct(card.dataset.open)});
$$(".filter").forEach(b=>b.addEventListener("click",()=>setCategory(b.dataset.category)));$("#sort").addEventListener("change",render);$(".bag").addEventListener("click",openDrawer);$(".close").addEventListener("click",closeDrawer);$(".continue").addEventListener("click",closeDrawer);$(".close-product").addEventListener("click",closeProduct);
overlay.addEventListener("click",()=>{if(!modal.hidden)closeProduct();if(drawer.classList.contains("open"))closeDrawer()});
$(".cart-lines").addEventListener("click",e=>{const b=e.target.closest("[data-qty]");if(!b)return;const item=cart.find(x=>x.id===b.dataset.id&&x.variant===b.dataset.variant);if(!item)return;item.qty+=Number(b.dataset.qty);if(item.qty<=0)cart=cart.filter(x=>x!==item);persist();updateCart()});
modal.addEventListener("click",e=>{const v=e.target.closest("[data-modal-variant]"),b=e.target.closest("[data-modal-add]");if(v){variants[v.dataset.modalVariant]=v.dataset.variant;modal.querySelectorAll("[data-modal-variant]").forEach(x=>{const selected=x.dataset.variant===v.dataset.variant;x.classList.toggle("selected",selected);x.setAttribute("aria-pressed",String(selected))})}if(b){add(b.dataset.modalAdd);closeProduct();openDrawer()}});
$(".search").addEventListener("click",()=>{const value=prompt("What are you looking for?");if(value===null)return;query=value.trim();setCategory("All");$("#shop").scrollIntoView({behavior:reduceMotion.matches?"instant":"smooth"})});
$$("[data-nav-category]").forEach(a=>a.addEventListener("click",()=>setCategory(a.dataset.navCategory)));
$(".menu").addEventListener("click",e=>{const open=$(".nav").classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",String(open))});$(".nav").addEventListener("click",e=>{if(e.target.closest("a")){$(".nav").classList.remove("open");$(".menu").setAttribute("aria-expanded","false")}});
$("#newsletter-form").addEventListener("submit",e=>{e.preventDefault();$(".feedback").textContent="You’re on the list. Look out for a little note from us.";e.currentTarget.reset()});$(".checkout").addEventListener("click",()=>say("Checkout is ready to connect to your store platform."));
document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(!modal.hidden)closeProduct();else if(drawer.classList.contains("open"))closeDrawer()}if(e.key!=="Tab")return;const dialog=!modal.hidden?modal:drawer.classList.contains("open")?drawer:null;if(!dialog)return;const focusable=[...dialog.querySelectorAll("button:not(:disabled),a[href],input,select,[tabindex]:not([tabindex='-1'])")].filter(x=>x.offsetParent!==null);if(!focusable.length)return;if(e.shiftKey&&document.activeElement===focusable[0]){e.preventDefault();focusable.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===focusable.at(-1)){e.preventDefault();focusable[0].focus()}});
render();updateCart();